# Generated by Django 4.1.5 on 2023-01-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0004_newproducts_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="img/")),
            ],
        ),
    ]
