# Generated by Django 4.1.5 on 2023-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0005_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
