# Generated by Django 4.1.5 on 2023-01-03 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0006_collection_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopSelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("price", models.FloatField()),
                ("old_price", models.FloatField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="img/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TopSellings",
            },
        ),
    ]
