# Generated by Django 4.1.5 on 2023-01-04 13:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0008_newproducts_description_newproducts_old_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newproducts",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="topselling",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
