# Generated by Django 4.1.5 on 2023-01-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0009_alter_newproducts_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topselling",
            name="discount_percent",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="topselling",
            name="status",
            field=models.CharField(
                blank=True, choices=[("new", "NEW")], max_length=50, null=True
            ),
        ),
    ]
