# Generated by Django 4.1.5 on 2023-01-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0010_topselling_discount_percent_topselling_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="topselling",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
