# Generated by Django 4.1.5 on 2023-01-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0012_newproducts_discount_percent_newproducts_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newproducts",
            name="quantity",
            field=models.IntegerField(
                blank=True,
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                null=True,
            ),
        ),
    ]
