# Generated by Django 4.1.5 on 2023-01-06 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0013_alter_newproducts_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newproducts",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="topselling",
            name="quantity",
        ),
    ]
