# Generated by Django 4.1.5 on 2023-01-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0014_remove_newproducts_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topselling",
            name="status",
            field=models.CharField(
                blank=True, choices=[("NEW", "NEW")], max_length=50, null=True
            ),
        ),
    ]
