# Generated by Django 4.1.5 on 2023-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0016_ordernp_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordernp",
            name="qty",
            field=models.IntegerField(default=1),
        ),
    ]
