# Generated by Django 4.1.5 on 2023-01-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0017_ordernp_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordernp",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
