# Generated by Django 4.1.5 on 2023-01-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0018_ordernp_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
