# Generated by Django 4.1.5 on 2023-01-09 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0019_delete_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordernp",
            name="slug",
        ),
    ]
