# Generated by Django 4.1.1 on 2023-01-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0020_remove_ordernp_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("address", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name="OrderNp",
            new_name="Cart",
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty", models.IntegerField(default=1)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.customer",
                    ),
                ),
                (
                    "np",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.newproducts",
                    ),
                ),
            ],
        ),
    ]
