# Generated by Django 4.1.5 on 2023-01-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0021_customer_rename_ordernp_cart_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="ts",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="electro.topselling",
            ),
        ),
    ]
