# Generated by Django 4.1.5 on 2023-01-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0022_cart_ts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="ts",
        ),
    ]
