# Generated by Django 4.1.5 on 2023-01-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0023_remove_cart_ts"),
    ]

    operations = [
        migrations.AddField(
            model_name="newproducts",
            name="color",
            field=models.CharField(
                choices=[
                    ("Red", "Red"),
                    ("Black", "Black"),
                    ("Blue", "Blue"),
                    ("White", "White"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="newproducts",
            name="qty",
            field=models.IntegerField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                null=True,
            ),
        ),
    ]
