# Generated by Django 4.1.5 on 2023-01-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0024_newproducts_color_newproducts_qty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newproducts",
            name="color",
        ),
        migrations.RemoveField(
            model_name="newproducts",
            name="qty",
        ),
    ]
