# Generated by Django 4.1.5 on 2023-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0025_remove_newproducts_color_remove_newproducts_qty"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="color",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
