# Generated by Django 4.1.5 on 2023-01-11 14:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0026_cart_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("price", models.FloatField()),
                ("old_price", models.FloatField(null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="img/")),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "discount_percent",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("sp", "smartphones"),
                            ("cm", "camera"),
                            ("acs", "accessories"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.category",
                    ),
                ),
            ],
        ),
    ]
