# Generated by Django 4.1.5 on 2023-01-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0027_items"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Items",
            new_name="Item",
        ),
    ]
