# Generated by Django 4.1.5 on 2023-01-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0028_rename_items_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("ts", "topselling"),
                    ("np", "newproducts"),
                    ("tp", "trendingproduct"),
                ],
                max_length=2,
            ),
        ),
    ]
