# Generated by Django 4.1.5 on 2023-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0029_alter_item_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("tp", "topselling"),
                    ("np", "newproducts"),
                    ("tp", "trendingproduct"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
