# Generated by Django 4.1.5 on 2023-01-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0030_category_item_type_delete_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="item_type",
        ),
        migrations.AddField(
            model_name="newproducts",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("tp", "topselling"),
                    ("np", "newproducts"),
                    ("tp", "trendingproduct"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
