# Generated by Django 4.1.5 on 2023-01-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0031_remove_category_item_type_newproducts_item_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="np",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="electro.cart"
            ),
        ),
    ]
