# Generated by Django 4.1.5 on 2023-01-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0033_alter_order_np"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
    ]
