# Generated by Django 4.1.5 on 2023-01-14 08:45

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0034_remove_order_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("ts", "topselling"),
                            ("np", "newproducts"),
                            ("tp", "trendingproduct"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, null=True, unique=True
                    ),
                ),
                ("price", models.FloatField()),
                ("old_price", models.FloatField(null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="img/")),
                ("description", ckeditor.fields.RichTextField(blank=True, null=True)),
                (
                    "discount_percent",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, choices=[("NEW", "NEW")], max_length=50, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="electro.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "NewProducts",
            },
        ),
        migrations.RemoveField(
            model_name="newproducts",
            name="category",
        ),
        migrations.DeleteModel(
            name="TopSelling",
        ),
        migrations.AlterField(
            model_name="cart",
            name="np",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="electro.products"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="np",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="electro.products"
            ),
        ),
        migrations.DeleteModel(
            name="NewProducts",
        ),
    ]
