# Generated by Django 4.1.5 on 2023-01-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0035_products_remove_newproducts_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name_plural": "Products"},
        ),
    ]
