# Generated by Django 4.1.1 on 2023-01-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0036_alter_products_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="slug",
            new_name="cat_slug",
        ),
    ]
