# Generated by Django 4.1.5 on 2023-02-04 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("electro", "0040_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="file",
        ),
        migrations.RemoveField(
            model_name="product",
            name="url",
        ),
    ]
